language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover

after_success:
  - coveralls
