# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='authors',
            field=models.ManyToManyField(null=True, to='home.Author'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
