# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180121_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='authors',
            field=models.ManyToManyField(to='home.Author'),
        ),
    ]
