# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180121_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='primary',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='secondary',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
