# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180121_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='id',
        ),
        migrations.AlterField(
            model_name='theme',
            name='key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
