# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180121_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
